cat > environment.yml << 'YAML'
name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake=7.32.4
  - fastp
  - star
  - samtools
  - subread
  - r-base=4.3
  - r-ggplot2
  - bioconductor-deseq2
  - pip
  - pip:
      - pandas
      - matplotlib
YAML

